source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!






target 'Collector_client' do
    pod 'Alamofire', '~> 3.0'
    pod 'AlamofireImage', '~> 2.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'BrightFutures'
end

target 'Collector_clientTests' do

end

target 'Collector_clientUITests' do

end
